#!/usr/bin/env bash

VERSION="4.2"
echo "Ubuntu Swift $VERSION Release Installer"

# Determine OS
UNAME=`uname`
if [[ $UNAME == "Darwin" ]]; then
    OS="macOS"
else
    if [[ $UNAME == "Linux" ]]; then
        UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`
        if [[ $UBUNTU_RELEASE == *"18.04"* ]]; then
            OS="ubuntu1804"
        elif [[ $UBUNTU_RELEASE == *"16.04"* ]]; then
            OS="ubuntu1604"
        else
            OS="ubuntu1404"
        fi
    else
        echo "Unsupported Operating System: $UNAME"
    fi
fi
echo "🖥  Operating System: $OS"

if [[ $OS != "macOS" ]]; then
    echo "📚 Installing Dependencies"
    sudo apt-get install -y clang libicu-dev
    if [[ $? != 0 ]]; then
        apt-get install -y clang libicu-dev
    fi

    echo "🐦 Installing Swift"
    PREFIX="swift-$VERSION-RELEASE"
    if [[ $OS == "ubuntu1804" ]]; then
        SWIFTFILE="$PREFIX-ubuntu18.04"
    elif [[ $OS == "ubuntu1604" ]]; then
        SWIFTFILE="$PREFIX-ubuntu16.04"
    else
        SWIFTFILE="$PREFIX-ubuntu14.04"
    fi
    BINLINK="https://swift.org/builds/swift-$VERSION-release/$OS/$PREFIX/$SWIFTFILE.tar.gz"
    if hash swiftenv 2>/dev/null; then
        echo "⚠️  Using swiftenv"
        swiftenv install $BINLINK
    else
        wget $BINLINK
        tar -zxf $SWIFTFILE.tar.gz
        export PATH=$PWD/$SWIFTFILE/usr/bin:"${PATH}"
        echo "export PATH=$PWD/$SWIFTFILE/usr/bin:"\${PATH}"" >> ~/.bashrc
        echo "✅ Done"
    fi
fi

echo "📅 Version: `swift --version`"
